### Get All Products
GET http://localhost:5000/api/products

### Get Single Product 
GET http://localhost:5000/api/products/1

###     Create New Product 
POST http://localhost:5000/api/products
Content-Type: application/json

{
 "title":"product2",
 "description":"h2", 
  "price":12
}
