### Get All Users
GET http://localhost:5000/api/users
//


### Register
POST http://localhost:5000/api/users/auth/register
Content-Type: application/json

{ 
  "email": "ENG.sanayoali4@gmail.com",
  "password": "123lvl56",
  "username": "sana"
}

### Login
POST http://localhost:5000/api/users/auth/login
Content-Type: application/json

{ 
  "email": "ENG.sanayoali4@gmail.com",
  "password": "123lvl56"
}